### ISSUE TITLE
Use this module name for a forward-compatible fs.realpath?

### ISSUE THREAD

**Issue by isaacs** [sindresorhus/realpath#1]
In Node 6, `fs.realpath` was changed in such a way that it can raise new errors and can no longer handle long paths or looped symbolic links.

I'd like to make a fill-in module that tries to use `fs.realpath`, and then, on Node 6 and above, handle those failures by falling back to the slower-but-more-resilient js implementation.

Would you be open to a PR to add a lib component to this module?

**Comment by sindresorhus** [comment]
I'm not interested in maintaining something like that and I think API and CLI should be separate modules, but I can give you the name and I can use `realpath-cli` for this module instead and depend on your module here. Sounds good?

**Comment by isaacs** [comment]
No worries, I'll use `fs.realpath` instead.

I'd recommend using that module once I publish it, rather than relying on Node's internal one, since v6 causes some unpleasantly breaking changes.  (If you prefer to have this cli realpath adhere more closely to the system realpath, though, then perhaps the changes in v6 are preferable.)

**Comment by sindresorhus** [comment]
Cool. Yeah, gonna use yours when it's out.

**Comment by isaacs** [comment]
Here you go! https://www.npmjs.com/package/fs.realpath

**Comment by sindresorhus** [comment]
Done.
